=== albim72/XML_podstawy_12/order/order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="http://example.com/order" 
           xmlns="http://example.com/order" 
           xmlns:ns="http://example.com/order" 
           elementFormDefault="qualified">

    <!-- Definicja głównego elementu Order -->
    <xs:element name="Order">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="OrderID" type="xs:string"/>
                <xs:element name="Customer">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Phone" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Items">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Item" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Name" type="xs:string"/>
                                        <xs:element name="Quantity" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== albim72/XML_podstawy_12/order/order.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:Order xmlns:ns="http://localhost/order"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://localhost/order http://localhost/order/order.xsd">
    <ns:OrderID>12345</ns:OrderID>
    <ns:Customer>
        <ns:Name>Janina Kowalska</ns:Name>
        <ns:Phone>+48123456789</ns:Phone>
    </ns:Customer>
    <ns:Items>
        <ns:Item>
            <ns:Name>Telefon</ns:Name>
            <ns:Quantity>1</ns:Quantity>
        </ns:Item>
        <ns:Item>
            <ns:Name>Laptop</ns:Name>
            <ns:Quantity>2</ns:Quantity>
        </ns:Item>
    </ns:Items>
</ns:Order>
