=== albim72/XML_podstawy_12/DTD/ucz5.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT uczelnia (nazwa,wydzial+)>
<!ELEMENT nazwa (#PCDATA)>
<!ELEMENT wydzial (#PCDATA|kierunek|instytuty)*>
<!ELEMENT kierunek (#PCDATA)>
<!ELEMENT instytuty (instytut+)>
<!ELEMENT instytut (#PCDATA)>

=== albim72/XML_podstawy_12/DTD/uczelnia5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE uczelnia SYSTEM "ucz5.dtd">
<uczelnia>
    <nazwa>Politechnika Śląska</nazwa>
    <wydzial>Automatyki, Elektroniki i Informatyki
        <instytuty>
            <instytut>Instytut Automatyki</instytut>
            <instytut>Instytut Elektroniki</instytut>
            <instytut>Instytut Informatyki</instytut>  
        </instytuty>
        Na wydziale dostępne są 3 szatnie!
    </wydzial>
    <wydzial>
        To jest wydział Matematyki i Fizyki prowadzący kierunek
        <kierunek>Matematyka</kierunek>
        oraz kierunek
        <kierunek>Fizyka</kierunek>
    </wydzial>

</uczelnia>
